### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by nastutusha** [FourPi/material-showcase-xamarin-ios#1]
I've noticed that you created a nuget for Android Bindings, could you please make it for iOS as well?

**Comment by beeradmoore** [comment]
Hey @nastutusha 
The [Android project](https://github.com/FourPi/MaterialShowcaseView) you are talking about is actually a fork of an [existing library](https://github.com/meysamrt/MaterialShowcaseView) with some changes that we use internally. The Nuget package you can find is of the original repo not one we have made.

I am not sure of what changes had been done as other devs had done the work, you'd have to check what changes have happened and see if you want to use our changes or just the original source.

The iOS project is a re-write of [this project](https://github.com/aromajoin/material-showcase-ios) directly into C# for a test but its still currently un-documented and the original developers are un-credited. We currently won't be creating a nuget of this package but if we do we'll be sure to add better documentation and original author credit before then. 

Unfortunately if you'd like to use either of these projects at the moment I would recommend pulling the code locally and either building release and taking the .dll out of /bin/Release/ directory or reference the .csproj directly.

**Comment by nastutusha** [comment]
Got it! Thank you for the clarification!
